VERSION = '0.4.0'
NAME_PROGRAM = 'Chinese Trainer'

COLOR_GREEN = "#00AA55"
COLOR_RED   = "#AA2222"
COLOR_GRAY  = "#DDDDDD"

FONT_BIG   = ("Arial", 100)  
FONT_SMALL = ("Arial", 18)  
FONT_SCORE = ("Arial", 30) 

WIDTH_MAIN_WINDOW = 1000
HEIGHT_MAIN_WINDOW= 600
POSX_MAIN_WINDOW = 400
POSY_MAIN_WINDOW = 200

WIDTH_DIAPASONE_WINDOW = 300
HEIGHT_DIAPASONE_WINDOW = 300
POSX_DIAPASONE_WINDOW = POSX_MAIN_WINDOW + WIDTH_MAIN_WINDOW/2 - WIDTH_DIAPASONE_WINDOW/2
POSY_DIAPASONE_WINDOW = POSY_MAIN_WINDOW